name: Feature Request
description: Suggest a new feature or improvement
title: "[FEATURE] "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Suggest a Feature

        Have an idea to make RTO Codes better? We'd love to hear it!

  - type: textarea
    id: problem
    attributes:
      label: Problem or Motivation
      description: Is this related to a problem? What's the motivation?
      placeholder: "I find it frustrating when..."
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution *
      description: What would you like to see?
      placeholder: "It would be great if the site could..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternatives?
      placeholder: "Another option could be..."
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: How important is this to you?
      options:
        - Nice to have
        - Would use it regularly
        - Really need this
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: Any sketches, screenshots, or examples from other sites?
      placeholder: "Drag and drop images or paste links..."
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information
    validations:
      required: false
